import React, { useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { AnimatePresence, motion, useScroll, useTransform } from "framer-motion";
import { ArrowUpRight, Bot, BrainCircuit, Check, ChevronDown, ChevronRight, Code2, Facebook, Gamepad2, Globe2, Instagram, Laptop2, Linkedin, Menu, MessageCircle, Palette, Play, Rocket, Search, Sparkles, X, Youtube } from "lucide-react";
import { categories, Course, courses } from "./data/courses";
import "./styles.css";

const ease = [0.25, 0.1, 0.25, 1] as const;

function FadeIn({ children, delay = 0, duration = 0.7, x = 0, y = 28, className = "" }: { children: React.ReactNode; delay?: number; duration?: number; x?: number; y?: number; className?: string }) {
  return <motion.div className={className} initial={{ opacity: 0, x, y }} whileInView={{ opacity: 1, x: 0, y: 0 }} viewport={{ once: true, margin: "50px", amount: 0 }} transition={{ duration, delay, ease }}>{children}</motion.div>;
}

function Magnet({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  const [pos, setPos] = useState({ x: 0, y: 0 });
  return <motion.div ref={ref} className={className} animate={{ x: pos.x, y: pos.y }} transition={{ type: "spring", stiffness: 220, damping: 16 }} onMouseMove={(e) => { const r = ref.current?.getBoundingClientRect(); if (r) setPos({ x: (e.clientX - r.left - r.width / 2) * 0.12, y: (e.clientY - r.top - r.height / 2) * 0.12 }); }} onMouseLeave={() => setPos({ x: 0, y: 0 })}>{children}</motion.div>;
}

function Robo({ small = false }: { small?: boolean }) {
  return <div className={`robo-wrap ${small ? "robo-small" : ""}`} aria-label="Robo, KapzCode mascot"><div className="robo-aura" /><div className="robo"><div className="robo-antenna" /><div className="robo-head"><div className="robo-face"><i /><i /></div><span className="robo-mouth" /></div><div className="robo-neck" /><div className="robo-body"><span className="robo-panel">KZ</span><span className="robo-light" /></div><div className="robo-arm left" /><div className="robo-arm right" /><div className="robo-shadow" /></div></div>;
}

function Navbar({ onLogin }: { onLogin: () => void }) {
  const [open, setOpen] = useState(false);
  const links = [["About", "about"], ["Courses", "courses"], ["How It Works", "how"], ["Admissions", "admissions"], ["Contact", "contact"]];
  return <motion.header className="navbar" initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }}>
    <a className="brand" href="#home"><span className="brand-icon"><Bot size={17} /></span><span>Kapz<span>Code</span></span></a>
    <nav className="desktop-nav">{links.map(([label, id]) => <a key={id} href={`#${id}`}>{label}</a>)}<button className="login-pill" onClick={onLogin}>Student Login <ArrowUpRight size={14} /></button></nav>
    <button className="menu-btn" aria-label="Toggle menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>
    <AnimatePresence>{open && <motion.nav className="mobile-nav" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }}>{links.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setOpen(false)}>{label}</a>)}<button className="login-pill" onClick={() => { onLogin(); setOpen(false); }}>Student Login <ArrowUpRight size={14} /></button></motion.nav>}</AnimatePresence>
  </motion.header>;
}

function SectionIntro({ eyebrow, title, description, light = false }: { eyebrow: string; title: string; description?: string; light?: boolean }) {
  return <div className={`section-intro ${light ? "light" : ""}`}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description && <p>{description}</p>}</div>;
}

function Hero({ onApply }: { onApply: () => void }) {
  return <section className="hero" id="home"><div className="hero-grid" /><div className="hero-content"><FadeIn delay={.15}><span className="eyebrow">THE FUTURE OF LEARNING</span></FadeIn><FadeIn delay={.15}><h1 className="hero-heading">Learn. Create. <em>Code.</em><br />Become Future Ready.</h1></FadeIn><FadeIn delay={.3}><p>KapzCode is a modern online school helping learners aged 7+ and adults build practical skills in coding, AI, technology, digital creativity, and future-focused learning.</p></FadeIn><FadeIn delay={.4} className="hero-actions"><a className="btn btn-primary" href="#courses">Explore Courses <ArrowUpRight size={17} /></a><button className="btn btn-outline" onClick={onApply}>Apply for Admission</button></FadeIn><div className="hero-tags">{["AI", "CODING", "CREATIVITY", "TECHNOLOGY", "DIGITAL SKILLS"].map((t, i) => <span key={t} style={{ animationDelay: `${i * .35}s` }}>{t}</span>)}</div></div><FadeIn delay={.5} className="hero-robo"><Magnet><Robo /></Magnet><div className="holo holo-one">{"</>"} <small>BUILD</small></div><div className="holo holo-two"><Sparkles size={14} /> AI <small>CREATE</small></div><div className="holo holo-three">WEB <small>LEARN</small></div></FadeIn><div className="scroll-cue">SCROLL TO EXPLORE <span /></div></section>;
}

const visualTiles = ["coding", "AI", "websites", "games", "digital art", "robotics", "online learning", "entrepreneurship"];
function LearningMarquee() {
  return <section className="marquee-section"><SectionIntro eyebrow="LEARNING IN MOTION" title="Learning in Motion" description="Explore a world where creativity, technology and practical learning come together." /><div className="marquee-viewport"><div className="marquee-row right">{[...visualTiles, ...visualTiles].map((name, i) => <div className={`visual-tile tile-${i % 8}`} key={`${name}-${i}`}><span>{name}</span><div className="tile-shape"><Code2 /></div></div>)}</div><div className="marquee-row left">{[...visualTiles.slice().reverse(), ...visualTiles.slice().reverse()].map((name, i) => <div className={`visual-tile tile-${(i + 3) % 8}`} key={`${name}-${i}`}><span>{name}</span><div className="tile-shape"><Sparkles /></div></div>)}</div></div></section>;
}

function About() {
  return <section className="section about" id="about"><div className="about-copy"><SectionIntro eyebrow="THE KAPZCODE APPROACH" title="Technology education, made real." description="KapzCode is an online learning platform created to make modern technology education practical, engaging, and accessible to learners of different ages." /><p>From young learners taking their first steps into coding to adults developing new digital skills, KapzCode encourages curiosity, creativity, problem solving, and hands-on learning.</p><p>Our goal is to help learners understand technology, create with it, and gain the confidence to turn ideas into real projects.</p><div className="stats"><div><strong>15</strong><span>Months of curriculum</span></div><div><strong>∞</strong><span>Ways to create</span></div><div><strong>7+</strong><span>Learning starts here</span></div></div></div><FadeIn x={40} className="image-frame"><img src="/images/kapzcode-classroom.jpeg" alt="Teacher and children learning with an AI robot in a classroom" /><div className="image-caption"><Bot size={18} /><span>Human curiosity<br /><b>meets machine possibility.</b></span></div></FadeIn></section>;
}

const categoriesInfo = [
  ["01", "AI & Digital Creativity", "Explore AI-powered art, design, storytelling, visual creation and creative problem solving.", Sparkles],
  ["02", "Web & Website Development", "Learn how websites are planned, designed, built, improved and presented.", Globe2],
  ["03", "Games & Interactive Projects", "Turn ideas into interactive experiences by designing games, characters, stories and gameplay.", Gamepad2],
  ["04", "AI & Chatbots", "Understand how AI assistants and chatbots are planned, designed, tested and improved.", MessageCircle],
  ["05", "Digital Media", "Create videos, reels, voiceovers, presentations and digital content using modern creative tools.", Play],
  ["06", "Entrepreneurship & Research", "Develop ideas, research real-world topics and communicate ideas professionally.", Rocket]
] as const;

function WhatLearn() {
  return <section className="section learn-section" id="learn"><SectionIntro eyebrow="YOUR CREATIVE TOOLKIT" title="What Can You Learn?" description="Build practical skills across AI, coding, digital creativity, technology and entrepreneurship." /><div className="learn-layout"><div className="category-grid">{categoriesInfo.map(([num, title, desc, Icon]) => <motion.article className="category-card" key={title} whileHover={{ y: -8, rotateX: 2, rotateY: -2 }} transition={{ duration: .3 }}><div className="card-top"><span>{num}</span><Icon size={22} /></div><h3>{title}</h3><p>{desc}</p><ArrowUpRight className="card-arrow" size={20} /></motion.article>)}</div><div className="technology-card"><img src="/images/kapzcode-technology.jpeg" alt="Futuristic technology and digital creativity illustration" /><div><span className="eyebrow">THE PLAYGROUND</span><h3>Ideas become interactive.</h3></div></div></div></section>;
}

function CourseCard({ course, onOpen }: { course: Course; onOpen: (c: Course) => void }) {
  return <motion.article className="course-card" layout whileHover={{ y: -5 }}><div className="course-meta"><span>MONTH {String(course.month).padStart(2, "0")}</span><span className="project-badge"><Sparkles size={12} /> PROJECT-BASED</span></div><h3>{course.title}</h3><span className="course-category">{course.category}</span><p>{course.description}</p><button onClick={() => onOpen(course)}>View Curriculum <ChevronRight size={16} /></button></motion.article>;
}

function CourseDetails({ course, onClose, onApply }: { course: Course; onClose: () => void; onApply: (course: Course) => void }) {
  return <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}><motion.div className="course-modal" initial={{ y: 30, scale: .96 }} animate={{ y: 0, scale: 1 }} onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={onClose}><X /></button><span className="eyebrow">MONTH {String(course.month).padStart(2, "0")} · {course.category}</span><h2>{course.title}</h2><p className="modal-description">{course.description}</p><div className="modal-columns"><div><h4>Learning activities</h4><ul>{course.activities.map(a => <li key={a}><Check size={15} />{a}</li>)}</ul></div><div><h4>Tools & examples</h4><div className="tool-list">{course.tools?.map(t => <span key={t}>{t}</span>)}</div><h4>Project outcome</h4><p>{course.outcome}</p><h4>Age suitability</h4><p>{course.ageGroups.join(" · ")}</p></div></div><button className="btn btn-primary" onClick={() => onApply(course)}>Apply for This Course <ArrowUpRight size={17} /></button></motion.div></motion.div>;
}

function Courses({ onApply }: { onApply: (course?: Course) => void }) {
  const [filter, setFilter] = useState("All"); const [age, setAge] = useState("All Ages"); const [selected, setSelected] = useState<Course | null>(null);
  const filtered = useMemo(() => courses.filter(c => (filter === "All" || c.category === filter || (filter === "Research" && c.category.includes("Research"))) && (age === "All Ages" || c.ageGroups.includes(age as "7+" | "Teens" | "Adults"))), [filter, age]);
  return <section className="section courses-section" id="courses"><SectionIntro eyebrow="THE KAPZCODE CURRICULUM" title="Explore Our Learning Programs" description="Follow a structured journey from your first creative experiment to building and presenting a complete capstone project." /><div className="course-filters"><div className="filter-scroll">{categories.map(c => <button className={filter === c ? "active" : ""} key={c} onClick={() => setFilter(c)}>{c}</button>)}</div><select aria-label="Filter by age" value={age} onChange={(e) => setAge(e.target.value)}>{["All Ages", "7+", "Teens", "Adults"].map(a => <option key={a}>{a}</option>)}</select></div><div className="course-grid">{filtered.map(c => <CourseCard key={c.id} course={c} onOpen={setSelected} />)}</div><div className="course-count"><span>{filtered.length} programs to explore</span><span>Curriculum grows with you <span className="dot" /></span></div><AnimatePresence>{selected && <CourseDetails course={selected} onClose={() => setSelected(null)} onApply={(c) => { setSelected(null); onApply(c); }} />}</AnimatePresence></section>;
}

const paths = [["01", "Kids 7+", "Start with curiosity.", "Explore creative technology, coding, AI, games and digital projects through engaging project-based learning."], ["02", "Teens", "Turn ideas into skills.", "Develop stronger technology, creative and entrepreneurial skills through structured projects."], ["03", "Adults", "Build skills for what's next.", "Explore practical digital and technology skills for personal development, career growth and new ideas."], ["04", "Future Creators", "Build something real.", "Move from learning individual skills toward creating complete projects and a final capstone."]];
function LearningPaths() { return <section className="paths-section"><div className="section"><SectionIntro eyebrow="FIND YOUR STARTING POINT" title="Choose Your Learning Path" description="There is no single way to become future ready. Find the pace, focus and challenge that feels right." /><div className="path-stack">{paths.map(([num, title, lead, desc], i) => <motion.article className="path-card" key={title} style={{ top: `${90 + i * 25}px` }} whileInView={{ scale: 1 - i * .035 }} viewport={{ once: true }}><span className="path-num">{num}</span><div><span className="eyebrow">PATH {num}</span><h3>{title}</h3><h4>{lead}</h4><p>{desc}</p></div><ArrowUpRight /></motion.article>)}</div></div></section>; }

function Why() { const items = [["01", "Project-Based Learning", "Students learn by creating real digital projects rather than only consuming theory.", Code2], ["02", "AI-Assisted Creativity", "Learn how modern AI tools can support creativity, research, design and problem solving.", BrainCircuit], ["03", "Technology Skills", "Build practical skills across coding, websites, games, chatbots and digital media.", Laptop2], ["04", "Learning for Different Ages", "Learning pathways can be structured for children, teenagers and adults.", Bot], ["05", "Portfolio Building", "Projects created during learning can eventually become part of a student's digital portfolio.", Palette], ["06", "Future Ready", "Develop confidence and skills that can support future education, projects and careers.", Rocket]] as const; return <section className="section why-section"><SectionIntro eyebrow="THE KAPZCODE DIFFERENCE" title="Why KapzCode?" /><div className="why-grid">{items.map(([num, title, desc, Icon]) => <FadeIn key={title}><article><span>{num}</span><Icon size={22} /><h3>{title}</h3><p>{desc}</p></article></FadeIn>)}</div></section>; }

function How() { const steps = [["01", "Explore", "Browse KapzCode's courses and discover areas that interest you."], ["02", "Apply", "Choose a course and submit the admission application."], ["03", "Learn & Build", "Take part in structured learning and create practical projects."], ["04", "Showcase", "Complete projects, build your portfolio and demonstrate what you have learned."]]; return <section className="section how-section" id="how"><div className="how-image"><img src="/images/kapzcode-online-learning.jpeg" alt="Learner studying online through a laptop" /></div><div className="how-content"><SectionIntro eyebrow="A SIMPLE START" title="How Learning Works" description="From the first spark of interest to a finished project, every step is designed to build confidence." /><div className="timeline">{steps.map(([num, title, desc], i) => <FadeIn delay={i * .1} key={title}><div className="timeline-step"><span>{num}</span><div><h3>{title}</h3><p>{desc}</p></div></div></FadeIn>)}</div></div></section>; }

function AdmissionForm({ selectedCourse, onDone }: { selectedCourse?: Course; onDone: () => void }) { const [sent, setSent] = useState(false); return <div className="admission-box">{sent ? <div className="confirmation"><Check size={40} /><span className="eyebrow">APPLICATION RECEIVED</span><h3>Thank you for applying.</h3><p>Our team will contact you with the next steps.</p><button className="btn btn-outline" onClick={onDone}>Close</button></div> : <form onSubmit={(e) => { e.preventDefault(); setSent(true); }}><div className="form-grid"><label>Student Name<input required placeholder="Your name" /></label><label>Parent/Guardian Name<input required placeholder="Parent or guardian name" /></label><label>Email<input required type="email" placeholder="you@example.com" /></label><label>Phone<input required placeholder="+00 000 000 000" /></label><label>Age<input required type="number" min="7" placeholder="Age" /></label><label>Course Interested In<select defaultValue={selectedCourse?.id ?? ""} required><option value="" disabled>Select a program</option>{courses.map(c => <option value={c.id} key={c.id}>Month {String(c.month).padStart(2, "0")} — {c.title}</option>)}</select></label><label>Current Education Level<input placeholder="School, college, professional..." /></label><label className="full">Message<textarea placeholder="Tell us what you would like to learn..." rows={4} /></label></div><button className="btn btn-primary" type="submit">Submit Application <ArrowUpRight size={17} /></button></form>}</div>; }

function Admissions({ selectedCourse, onClose }: { selectedCourse?: Course; onClose: () => void }) { return <section className="section admissions" id="admissions"><div className="admission-copy"><span className="eyebrow">YOUR NEXT CHAPTER</span><h2>Start Your Learning Journey</h2><p>Ready to learn something new? Apply to KapzCode and take the next step toward building practical technology and digital skills.</p><div className="admission-contact"><span>Prefer to talk first?</span><a href="mailto:hello@kapzcode.com">Talk to KapzCode <ArrowUpRight size={15} /></a></div></div><AdmissionForm selectedCourse={selectedCourse} onDone={onClose} /></section>; }

function Portal({ onOpen }: { onOpen: () => void }) { return <section className="section portal-section"><div><SectionIntro eyebrow="COMING NEXT" title="Your Learning Journey, All in One Place" description="KapzCode is being designed as more than an online course platform. Students will eventually have a personal digital space to track their learning journey." /><button className="btn btn-primary" onClick={onOpen}>Student Portal <ArrowUpRight size={17} /></button></div><div className="dashboard"><div className="dashboard-bar"><span className="brand"><span className="brand-icon"><Bot size={13} /></span>KapzCode</span><span className="avatar">K</span></div><div className="dashboard-grid"><div className="profile-widget"><span className="avatar large">K</span><b>Student profile</b><small>Future Creator</small></div><div className="progress-widget"><small>Course progress</small><strong>68%</strong><div className="progress"><i /></div><span>AI Art & Poster Project</span></div><div className="dash-widget"><span><Rocket size={15} />Projects</span><b>08</b></div><div className="dash-widget"><span><Sparkles size={15} />Certificates</span><b>03</b></div><div className="dash-widget wide"><span><Check size={15} />Recent achievement</span><b>Created a digital storybook</b></div></div><div className="dashboard-nav">Profile · Courses · Progress · Portfolio · Results</div></div></section>; }

const faqs = [["What age groups does KapzCode support?", "KapzCode is designed around learning opportunities for learners aged 7+ as well as teenagers and adults. Specific age suitability can vary by program."], ["What does KapzCode teach?", "KapzCode focuses on coding, AI, digital creativity, websites, games, chatbots, digital media, entrepreneurship, research and other future-focused skills."], ["Are the courses project-based?", "Yes. The curriculum is designed around practical projects and activities that allow learners to create while they learn."], ["How do I apply?", "Choose a course and complete the KapzCode admission application."], ["Will students have a portfolio?", "The future KapzCode student system is planned to include student portfolios where projects and achievements can be displayed."], ["Will parents be able to track progress?", "The future student system is planned to provide learning progress and academic information."]];
function FAQ() { const [open, setOpen] = useState(0); return <section className="section faq-section" id="faq"><SectionIntro eyebrow="GOOD TO KNOW" title="Frequently Asked Questions" /><div className="faq-list">{faqs.map(([q, a], i) => <div className={`faq-item ${open === i ? "open" : ""}`} key={q}><button onClick={() => setOpen(open === i ? -1 : i)}><span>{q}</span>{open === i ? <X size={18} /> : <ChevronDown size={18} />}</button><AnimatePresence>{open === i && <motion.p initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }}>{a}</motion.p>}</AnimatePresence></div>)}</div></section>; }

function CTA({ onApply }: { onApply: () => void }) { return <section className="cta-section"><div className="cta-orbit one" /><div className="cta-orbit two" /><div className="cta-copy"><span className="eyebrow">READY WHEN YOU ARE</span><h2>Your Future Starts With What You Learn Today.</h2><p>Explore KapzCode, discover your interests, build practical skills and turn your ideas into real projects.</p><div className="hero-actions"><a className="btn btn-primary" href="#courses">Explore Courses <ArrowUpRight size={17} /></a><button className="btn btn-outline" onClick={onApply}>Apply Now</button></div></div><div className="cta-robo"><Robo small /></div></section>; }

function Footer({ onLogin }: { onLogin: () => void }) { const socials = [[Facebook, "Facebook"], [Instagram, "Instagram"], [Linkedin, "LinkedIn"], [Youtube, "YouTube"]] as const; return <footer id="contact"><div className="footer-main"><div className="footer-brand"><a className="brand" href="#home"><span className="brand-icon"><Bot size={17} /></span><span>Kapz<span>Code</span></span></a><p>Learn. Create. Code.<br />Become Future Ready.</p><div className="socials">{socials.map(([I, n]) => <a href="#" aria-label={n} key={n}><I size={17} /></a>)}</div></div><div className="footer-col"><b>EXPLORE</b><a href="#courses">Courses</a><a href="#about">About</a><a href="#learn">Learning Paths</a><a href="#how">How It Works</a></div><div className="footer-col"><b>ADMISSIONS</b><a href="#admissions">Apply</a><a href="#admissions">Admission Information</a><a href="mailto:hello@kapzcode.com">Contact</a></div><div className="footer-col"><b>STUDENT</b><button onClick={onLogin}>Student Login</button><button onClick={onLogin}>Student Portal</button><a href="#courses">Portfolio</a></div><div className="footer-col"><b>COMPANY</b><a href="#about">About KapzCode</a><a href="#faq">FAQs</a><a href="mailto:hello@kapzcode.com">Contact</a></div></div><div className="footer-bottom"><span>© 2026 KapzCode. All rights reserved.</span><span>Built for future creators <Sparkles size={13} /></span></div></footer>; }

function App() {
  const [selectedCourse, setSelectedCourse] = useState<Course>(); const [toast, setToast] = useState(false);
  const apply = (course?: Course) => { setSelectedCourse(course); setTimeout(() => document.getElementById("admissions")?.scrollIntoView({ behavior: "smooth" }), 20); };
  const openPortal = () => { setToast(true); window.setTimeout(() => setToast(false), 3500); };
  return <><Navbar onLogin={openPortal} /><main><Hero onApply={() => apply()} /><LearningMarquee /><About /><WhatLearn /><Courses onApply={apply} /><LearningPaths /><Why /><How /><Admissions selectedCourse={selectedCourse} onClose={() => undefined} /><Portal onOpen={openPortal} /><FAQ /><CTA onApply={() => apply()} /></main><Footer onLogin={openPortal} /><AnimatePresence>{toast && <motion.div className="toast" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 20 }}><Bot size={20} /><div><b>Student Portal Coming Soon</b><span>Your personal learning dashboard will be available here.</span></div><button onClick={() => setToast(false)}><X size={16} /></button></motion.div>}</AnimatePresence></>;
}

createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
